words:
  - avenir
  - clsx
  - grayscale
  - reekystive
  - WCAG
flagWords:
  - blacklist -> blocklist
  - whitelist -> allowlist
suggestWords:
  - colour -> color
ignorePaths:
  - cspell.config.yaml
